import ical, { ICalEventData } from 'ical-generator';

/**
 * Generate an iCalendar (.ics) file for an interview
 * This can be attached to emails so recipients can add the event to their calendar
 */
export function generateInterviewCalendarInvite(params: {
  candidateName: string;
  candidateEmail: string;
  employerName: string;
  jobTitle: string;
  startTime: Date;
  duration: number; // in minutes
  type: string; // PHONE, VIDEO, ONSITE
  location?: string;
  meetingLink?: string;
  notes?: string;
}): string {
  const {
    candidateName,
    candidateEmail,
    employerName,
    jobTitle,
    startTime,
    duration,
    type,
    location,
    meetingLink,
    notes,
  } = params;

  // Calculate end time
  const endTime = new Date(startTime.getTime() + duration * 60 * 1000);

  // Create calendar
  const calendar = ical({
    name: 'Interview Schedule',
    prodId: {
      company: 'Job Portal',
      product: 'Interview Scheduler',
    },
  });

  // Prepare event description
  let description = `Interview for ${jobTitle}\n\n`;
  description += `Candidate: ${candidateName}\n`;
  description += `Company: ${employerName}\n`;
  description += `Type: ${type}\n`;

  if (meetingLink) {
    description += `\nMeeting Link: ${meetingLink}\n`;
  }

  if (location) {
    description += `\nLocation: ${location}\n`;
  }

  if (notes) {
    description += `\nNotes: ${notes}\n`;
  }

  description += '\n---\nGenerated by Job Portal';

  // Prepare event location
  let eventLocation = '';
  if (type === 'VIDEO' && meetingLink) {
    eventLocation = `Video Call: ${meetingLink}`;
  } else if (type === 'ONSITE' && location) {
    eventLocation = location;
  } else if (type === 'PHONE') {
    eventLocation = 'Phone Interview';
  }

  // Create event
  const eventData: ICalEventData = {
    start: startTime,
    end: endTime,
    summary: `Interview: ${jobTitle} - ${employerName}`,
    description,
    location: eventLocation,
    organizer: {
      name: employerName,
      email: 'noreply@jobportal.com',
    },
    attendees: [
      {
        name: candidateName,
        email: candidateEmail,
        rsvp: true,
        role: 'REQ-PARTICIPANT',
      },
    ],
    status: 'CONFIRMED',
    busyStatus: 'BUSY',
    method: 'REQUEST',
  };

  // Add meeting link as URL if it's a video interview
  if (meetingLink) {
    eventData.url = meetingLink;
  }

  calendar.createEvent(eventData);

  // Return the calendar as a string
  return calendar.toString();
}

/**
 * Generate calendar invite for interview cancellation
 */
export function generateInterviewCancellationInvite(params: {
  candidateName: string;
  candidateEmail: string;
  employerName: string;
  jobTitle: string;
  originalStartTime: Date;
  duration: number;
}): string {
  const {
    candidateName,
    candidateEmail,
    employerName,
    jobTitle,
    originalStartTime,
    duration,
  } = params;

  const endTime = new Date(originalStartTime.getTime() + duration * 60 * 1000);

  const calendar = ical({
    name: 'Interview Cancellation',
    prodId: {
      company: 'Job Portal',
      product: 'Interview Scheduler',
    },
    method: 'CANCEL',
  });

  calendar.createEvent({
    start: originalStartTime,
    end: endTime,
    summary: `CANCELLED: Interview - ${jobTitle} - ${employerName}`,
    description: `This interview has been cancelled.\n\nOriginal Details:\nCandidate: ${candidateName}\nCompany: ${employerName}\nPosition: ${jobTitle}`,
    organizer: {
      name: employerName,
      email: 'noreply@jobportal.com',
    },
    attendees: [
      {
        name: candidateName,
        email: candidateEmail,
      },
    ],
    status: 'CANCELLED',
    method: 'CANCEL',
  });

  return calendar.toString();
}
